# Generated by Django 4.2.6 on 2023-10-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Euler_NM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=63)),
                ('resultado', models.FloatField(default=0.0)),
                ('tiempo', models.PositiveIntegerField(default=0)),
                ('ciclos', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
