# Generated by Django 4.2.6 on 2023-10-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euler_nm',
            name='ciclos',
        ),
        migrations.RemoveField(
            model_name='euler_nm',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='euler_nm',
            name='N',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='euler_nm',
            name='a',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='euler_nm',
            name='f',
            field=models.CharField(default='x', max_length=255),
        ),
        migrations.AddField(
            model_name='euler_nm',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='euler_nm',
            name='x0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='euler_nm',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='euler_nm',
            name='y0',
            field=models.FloatField(default=0.0),
        ),
    ]
