# Generated by Django 4.2.6 on 2023-10-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_euler_nm_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='euler_nm',
            name='h',
            field=models.FloatField(default=0.0),
        ),
    ]
