# Generated by Django 4.2.6 on 2023-10-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_euler_nm_h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euler_nm',
            name='y',
        ),
    ]
